/* 🤖 this file was generated by svg-to-ts*/
export const chevron: {
  name: 'chevron';
  data: string;
} = {
  name: 'chevron',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 5"><path d="M.854 1.054A.5.5 0 011.207.2h7.586a.5.5 0 01.353.854L5.707 4.493a1 1 0 01-1.414 0l-3.44-3.44z" fill="#000"/></svg>`
};
export const cloud: {
  name: 'cloud';
  data: string;
} = {
  name: 'cloud',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 23"><path opacity=".5" d="M40 16c0-8.837-6.268-16-14-16-5.44 0-10.155 3.546-12.473 8.726-.569 1.272-2.2 1.863-3.55 1.52A8 8 0 000 18c-.001 1.685 2.182 2.109 4.013 2.464.304.06.597.116.87.177l.462.103a67.55 67.55 0 0029.308 0l.462-.103c.273-.06.566-.118.87-.177C37.817 20.11 40 19.685 40 18v-2z" fill="#B5C7FF"/></svg>`
};
export const search: {
  name: 'search';
  data: string;
} = {
  name: 'search',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 20"><path fill-rule="evenodd" clip-rule="evenodd" d="M15 7.5a7.5 7.5 0 11-15 0 7.5 7.5 0 0115 0zm-2 0a5.5 5.5 0 11-11 0 5.5 5.5 0 0111 0z" fill="#08153E"/><path d="M14.5 14.379a1 1 0 00-1.414 0l-.707.707a1 1 0 000 1.414l2.475 2.475a1.5 1.5 0 102.12-2.122L14.5 14.38z" fill="#08153E"/></svg>`
};
export const spinner: {
  name: 'spinner';
  data: string;
} = {
  name: 'spinner',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M18.966 10.784A9 9 0 119.05 1.05" stroke="#08153E" stroke-width="2" stroke-linecap="round"/></svg>`
};
export const sun: {
  name: 'sun';
  data: string;
} = {
  name: 'sun',
  data: `<svg fill="none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 18"><path d="M14 2a2 2 0 114 0v2a2 2 0 11-4 0V2zM2 18a2 2 0 110-4h2a2 2 0 110 4H2zM4.686 7.515a2 2 0 112.829-2.829l1.414 1.415a2 2 0 11-2.828 2.828L4.686 7.515zM8.041 16.814a8 8 0 0112.542-7.372c-2.066 1.696-3.743 3.924-4.881 6.467-.035.078-.144.221-.412.33-.272.111-.58.13-.821.069A10.015 10.015 0 0012 16c-1.406 0-2.745.29-3.959.814z" fill="#FFD600"/></svg>`
};
export type svgIcon = 'chevron' | 'cloud' | 'search' | 'spinner' | 'sun';
export interface SvgIcon {
  name: svgIcon;
  data: string;
}
export type IconNameSubset<T extends Readonly<SvgIcon[]>> = T[number]['name'];
